language: node_js
node_js:
  - 9.11.1
env:
  - DB=pgsql
addons:
  postgresql: "9.4"
services:
  - postgresql
postgres:
  adapter: postgresql
  database: MY_APP_test
  username: postgres
before_install:
  - gem install bundler
  - bundle install
cache:
  bundler: true
  directories:
    - ~/.npm
    - ~/.cache
    - "node_modules"
install:
  - npm install
before_script:
  - rails server &
  - "psql -c 'create database MY_APP_test;' -U postgres"
  - "rake db:migrate"
script:
  - $(npm bin)/cypress run