language: node_js
node_js:
  - 9.11.1
addons:
  postgresql: "9.4"
services:
  - postgresql
before_install:
  - gem install bundler
  - bundle install
cache:
  yarn: true
  bundler: true
  directories:
    - ~/.cache
env:
  - BUNDLE_GEMS__CONTRIBSYS__COM=79aa1ad6:74b84d60
install:
  - yarn add cypress
before_script:
  - rails server &
  - psql -c 'create database travis_ci_test;' -U postgres
  - rails db:migrate
  - RAILS_ENV=test bundle exec rake db:seed
script:
  - $(yarn bin)/cypress run