language: node_js
node_js:
  - 9.11.2
addons:
  postgresql: "9.4"
services:
  - redis-server
  - postgresql
cache:
  bundler: true
  yarn: true
  directories:
    - ~/.cache
env:
  - BUNDLE_GEMS__CONTRIBSYS__COM=79aa1ad6:74b84d60
before_install:
  - gem install bundler
  - bundle install 
install:
  - yarn add cypress
before_script:
  - bundle exec rails server -p 5002 -b 127.0.0.1 -d
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test 
script:
  - $(yarn bin)/cypress run
after_failure:
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
  - "lsof -wni tcp:3000"
  - "lsof -i tcp:3000"
  - "lsof -wni tcp:5002"
  - "lsof -wni tcp:8000"
  - "fuser 3000/tcp"
  
