language: ruby
cache:
  directories:
    - ~/.npm
    - ~/.cache
script:
  - $(npm bin)/cypress run
install:
  - bundle install
  - nvm install node
  - npm install
  - node -v
  - npm i -g yarn
  - yarn
  - yarn add cypress --save-dev