language: node_js
node_js:
  - 9.11.1
env:
  - DB=pgsql
addons:
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
    postgresql: 10
env:
  global:
    - PGPORT=5433
services:
  - postgresql
postgres:
  adapter: postgresql
  database: MY_APP_test
  username: postgres
before_install:
  - gem install bundler
  - bundle install
cache:
  bundler: true
  directories:
    - ~/.npm
    - ~/.cache
    - "node_modules"
install:
  - npm install
before_script:
  - rails server &
  - psql -c 'create database MY_APP_test;' -U postgres
script:
  - $(npm bin)/cypress run
