language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
before_install:
  - bundle install
before_script:
  - psql -c 'create database test_db;' -U postgres
install:
  - npm install cypress --save-dev
  - nvm install node
  - npm install
  - node -v
script:
  - $(npm bin)/cypress run --record