language: node_js
node_js:
  - 9.11.1
addons:
  postgresql: "10.3"
before_install:
  - gem install bundler
  - bundle install
before_script:
- cp config/database.yml.travis config/database.yml
cache:
  directories:
    - ~/.npm
    - ~/.cache
    - "node_modules"
install:
  - npm install
script:
  - $(npm bin)/cypress run