language: node_js
node_js:
  - 9.11.1
env:
  - DB=pgsql
addons:
  postgresql: "9.4"
services:
  - postgresql
before_install:
  - gem install bundler
  - bundle install
cache:
  bundler: true
  directories:
    - ~/.npm
    - ~/.cache
    - "node_modules"
install:
  - npm install
before_script:
  - rails server &
  - psql -c 'create database MY_APP_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - $(npm bin)/cypress run